# OPENAI/CHAT GPT
OPENAI="OPENAI_API"
OPENAI_MODEL_GPT_4O_MINI="gpt-4o-mini"
OPENAI_MODEL_GPT_41_MINI="gpt-4.1-mini"
OPENAI_MODEL_GPT_5_NANO="gpt-5-nano"
OPENAI_MODEL_GPT_5_MINI="gpt-5-mini"
OPENAI_MODEL_GPT_o3_MINI="o3-mini"

# GOOGLE/GEMINI
GEMINI="GOOGLE_API"
GEMINI_MODEL_GEMINI_25_FLASH="gemini-2.5-flash"

# GROQ
GROQ="GROQ_API"
GROQ_MODEL_GPT_OSS="openai/gpt-oss-120b"
GROQ_MODEL_LLAMA_3370B_VERSATILE="llama-3.3-70b-versatile"

# OLLAMA
OLLAMA="OLLAMA_API"
LLAMA_MODEL_32 = "llama3.2"

#DEEPSEEK
DEEPSEEK="DEEPSEEK_API"

# ANTHROPIC/CLAUDE
ANTHROPIC="ANTHROPIC_API"
CLAUDE_3_5_SONNET="claude-3-5-sonnet-20241022"

